//
//  GridRowCol.h
//  FlexGrid
//
//  Copyright (c) GrapeCity, Inc. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "GridRowColCollection.h"

/**
*  グリッド行または列の状態を指定するフラグ
*/
typedef NS_ENUM (NSInteger, GridRowColFlags){
/**
*  表示された状態
*/
    GridRowColFlagsVisible = 1,
/**
*  サイズ変更可能
*/
    GridRowColFlagsAllowResizing = 2,
/**
*  ドラッグ可能
*/
    GridRowColFlagsAllowDragging = 4,
/**
*  行/列は結合可能
*/
    GridRowColFlagsAllowMerging = 8,
/**
*  ソートが可能
*/
    GridRowColFlagsAllowSorting = 16,
/**
*  列を自動的に生成
*/
    GridRowColFlagsAutoGenerated = 32,
/**
*  行は折りたたまれている
*/
    GridRowColFlagsCollapsed = 64,
/**
*  親の行が折りたたまれている
*/
    GridRowColFlagsParentCollapsed = 128,
/**
*  選択可能
*/
    GridRowColFlagsSelected = 256,
/**
*  読み取り専用
*/
    GridRowColFlagsReadOnly = 512,
/**
*  HTMLコンテンツを含む
*/
    GridRowColFlagsHtmlContent = 1024,
/**
*  ワードラップが有効
*/
    GridRowColFlagsWordWrap = 2048,
/**
*  行のデフォルト設定
*/
    GridRowColFlagsRowDefault = GridRowColFlagsVisible | GridRowColFlagsAllowResizing,
/**
*  列のデフォルト設定
*/
    GridRowColFlagsColumnDefault = GridRowColFlagsVisible | GridRowColFlagsAllowDragging | GridRowColFlagsAllowResizing | GridRowColFlagsAllowSorting
};

/**
*  GridRowCol クラス
*/
@interface GridRowCol : NSObject

/**
*  GridRowCol オブジェクトを初期化します。
*    @return GridRowCol オブジェクト
*/
- (id)init;

/**
*  この行または列が表示されているかどうかを取得または設定します。
*/
@property (nonatomic) BOOL visible;

/**
*  この行または列が表示されている（折りたたまれていない）かどうかを取得します。
*/
@property (readonly) BOOL isVisible;

/**
*  この行または列の位置を取得します。
*/
@property (readonly) int pos;

/**
*  親コレクション内のこの行または列のインデックスを取得します。
*/
@property (readonly) int index;

/**
*  この行または列のサイズを取得または設定します。
*/
@property (nonatomic) int size;

/**
*  この行または列のレンダリングサイズを取得します。
*/
@property (readonly) int renderSize;

/**
*  ユーザーがこの行または列をサイズ変更できるかどうかを取得または設定します。
*/
@property (nonatomic) BOOL allowResizing;

/**
*  この行または列に含まれるセルがマージ（結合）可能かどうかを取得または設定します。
*/
@property (nonatomic) BOOL allowMerging;

/**
*  この行または列が選択されているかどうかを取得または設定します。
*/
@property (nonatomic) BOOL isSelected;

/**
*  この行または列にあるセルを編集できるかどうかを取得または設定します。
*/
@property (nonatomic) BOOL isReadOnly;

/**
*  この行または列にあるセルが内容を折り返し（ワードラップ）するかどうかを取得または設定します。
*/
@property (nonatomic) BOOL wordWrap;

/**
*  この行または列を所有する FlexGrid を取得します。
*/
@property (readonly) FlexGrid *grid;


@end
